export const MonacoConfig = {
  tokenColorCustomizations: {},
  semanticTokenColorCustomizations: {},
  tabSize: 4,
  indentSize: "tabSize",
  insertSpaces: false,
  detectIndentation: true,
  trimAutoWhitespace: true,
  largeFileOptimizations: true,
  wordBasedSuggestions: "matchingDocuments",
  semanticHighlighting: {
    enabled: "configuredByTheme",
  },
  stablePeek: false,
  maxTokenizationLineLength: 20000,
  experimental: {
    asyncTokenization: false,
    asyncTokenizationLogging: false,
    asyncTokenizationVerification: false,
    dropIntoEditor: {
      defaultProvider: {},
    },
  },
  acceptSuggestionOnCommitCharacter: true,
  acceptSuggestionOnEnter: "on",
  accessibilitySupport: "auto",
  accessibilityPageSize: 10,
  autoClosingBrackets: "languageDefined",
  autoClosingComments: "languageDefined",
  screenReaderAnnounceInlineSuggestion: true,
  autoClosingDelete: "auto",
  autoClosingOvertype: "auto",
  autoClosingQuotes: "languageDefined",
  autoIndent: "full",
  autoSurround: "languageDefined",
  automaticLayout: true,
  bracketPairColorization: {
    enabled: true,
    independentColorPoolPerBracketType: false,
  },
  guides: {
    bracketPairs: false,
    bracketPairsHorizontal: "active",
    highlightActiveBracketPair: true,
    indentation: true,
    highlightActiveIndentation: true,
  },
  codeLens: true,
  codeLensFontFamily: "",
  codeLensFontSize: 0,
  colorDecorators: true,
  colorDecoratorsLimit: 500,
  columnSelection: false,
  comments: {
    insertSpace: true,
    ignoreEmptyLines: true,
  },
  copyWithSyntaxHighlighting: true,
  cursorBlinking: "blink",
  cursorSmoothCaretAnimation: "off",
  cursorStyle: "line",
  cursorSurroundingLines: 0,
  cursorSurroundingLinesStyle: "default",
  cursorWidth: 0,
  dragAndDrop: true,
  dropIntoEditor: {
    enabled: true,
    showDropSelector: "afterDrop",
  },
  emptySelectionClipboard: true,
  experimentalWhitespaceRendering: "svg",
  fastScrollSensitivity: 5,
  find: {
    cursorMoveOnType: true,
    seedSearchStringFromSelection: "always",
    autoFindInSelection: "never",
    addExtraSpaceOnTop: true,
    loop: true,
  },
  folding: true,
  foldingStrategy: "auto",
  foldingHighlight: true,
  foldingImportsByDefault: false,
  foldingMaximumRegions: 5000,
  unfoldOnClickAfterEndOfLine: false,
  fontFamily: "'Droid Sans Mono', 'monospace', monospace",
  fontLigatures: false,
  fontSize: 14,
  fontWeight: "normal",
  fontVariations: false,
  formatOnPaste: false,
  formatOnType: false,
  glyphMargin: true,
  gotoLocation: {
    multiple: null,
    multipleDefinitions: "peek",
    multipleTypeDefinitions: "peek",
    multipleDeclarations: "peek",
    multipleImplementations: "peek",
    multipleReferences: "peek",
    alternativeDefinitionCommand: "editor.action.goToReferences",
    alternativeTypeDefinitionCommand: "editor.action.goToReferences",
    alternativeDeclarationCommand: "editor.action.goToReferences",
    alternativeImplementationCommand: "",
    alternativeReferenceCommand: "",
  },
  hideCursorInOverviewRuler: false,
  hover: {
    enabled: true,
    delay: 300,
    sticky: true,
    hidingDelay: 300,
    above: true,
  },
  inlineSuggest: {
    enabled: true,
    showToolbar: "onHover",
    suppressSuggestions: false,
    fontFamily: "default",
  },
  experimentalInlineEdit: {
    enabled: false,
    showToolbar: "onHover",
    fontFamily: "default",
    backgroundColoring: false,
  },
  letterSpacing: 0,
  lightbulb: {
    enabled: "on",
  },
  lineHeight: 0,
  lineNumbers: "on",
  linkedEditing: false,
  links: true,
  matchBrackets: "always",
  minimap: {
    enabled: true,
    autohide: false,
    size: "proportional",
    side: "right",
    showSlider: "mouseover",
    scale: 1,
    renderCharacters: true,
    maxColumn: 120,
    showRegionSectionHeaders: true,
    showMarkSectionHeaders: true,
    sectionHeaderFontSize: 9,
    sectionHeaderLetterSpacing: 1,
  },
  mouseWheelScrollSensitivity: 1,
  mouseWheelZoom: false,
  multiCursorMergeOverlapping: true,
  multiCursorModifier: "alt",
  multiCursorPaste: "spread",
  multiCursorLimit: 10000,
  occurrencesHighlight: "singleFile",
  overviewRulerBorder: true,
  padding: {
    top: 0,
    bottom: 0,
  },
  pasteAs: {
    enabled: true,
    showPasteSelector: "afterPaste",
  },
  parameterHints: {
    enabled: true,
    cycle: true,
  },
  peekWidgetDefaultFocus: "tree",
  definitionLinkOpensInPeek: false,
  quickSuggestions: {
    other: "on",
    comments: "off",
    strings: "off",
  },
  quickSuggestionsDelay: 10,
  renameOnType: false,
  renderControlCharacters: true,
  renderFinalNewline: "dimmed",
  renderLineHighlight: "line",
  renderLineHighlightOnlyWhenFocus: false,
  renderWhitespace: "selection",
  roundedSelection: true,
  rulers: [],
  scrollbar: {
    vertical: "auto",
    horizontal: "auto",
    verticalScrollbarSize: 14,
    horizontalScrollbarSize: 12,
    scrollByPage: false,
    ignoreHorizontalScrollbarInContentHeight: false,
  },
  scrollBeyondLastColumn: 4,
  scrollBeyondLastLine: true,
  scrollPredominantAxis: true,
  selectionClipboard: true,
  selectionHighlight: true,
  showFoldingControls: "mouseover",
  showUnused: true,
  snippetSuggestions: "inline",
  smartSelect: {
    selectLeadingAndTrailingWhitespace: true,
    selectSubwords: true,
  },
  smoothScrolling: false,
  stickyScroll: {
    enabled: true,
    maxLineCount: 5,
    defaultModel: "outlineModel",
    scrollWithEditor: true,
  },
  stickyTabStops: false,
  suggest: {
    insertMode: "insert",
    filterGraceful: true,
    localityBonus: false,
    shareSuggestSelections: false,
    selectionMode: "always",
    snippetsPreventQuickSuggestions: false,
    showIcons: true,
    showStatusBar: false,
    preview: false,
    showInlineDetails: true,
    maxVisibleSuggestions: 0,
    filteredTypes: {},
    showMethods: true,
    showFunctions: true,
    showConstructors: true,
    showDeprecated: true,
    matchOnWordStartOnly: true,
    showFields: true,
    showVariables: true,
    showClasses: true,
    showStructs: true,
    showInterfaces: true,
    showModules: true,
    showProperties: true,
    showEvents: true,
    showOperators: true,
    showUnits: true,
    showValues: true,
    showConstants: true,
    showEnums: true,
    showEnumMembers: true,
    showKeywords: true,
    showWords: true,
    showColors: true,
    showFiles: true,
    showReferences: true,
    showCustomcolors: true,
    showFolders: true,
    showTypeParameters: true,
    showSnippets: true,
    showUsers: true,
    showIssues: true,
  },
  suggestFontSize: 0,
  suggestLineHeight: 0,
  suggestOnTriggerCharacters: true,
  suggestSelection: "first",
  tabCompletion: "off",
  unicodeHighlight: {
    nonBasicASCII: "inUntrustedWorkspace",
    invisibleCharacters: true,
    ambiguousCharacters: true,
    includeComments: "inUntrustedWorkspace",
    includeStrings: true,
    allowedCharacters: {},
    allowedLocales: {
      _os: true,
      _vscode: true,
    },
  },
  unusualLineTerminators: "prompt",
  useTabStops: true,
  wordBreak: "normal",
  wordSegmenterLocales: null,
  wordSeparators: "`~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?",
  wordWrap: "off",
  wordWrapColumn: 80,
  wrappingIndent: "same",
  wrappingStrategy: "simple",
  showDeprecated: true,
  inlayHints: {
    enabled: "on",
    fontSize: 0,
    fontFamily: "",
    padding: false,
  },
  tabFocusMode: false,
  defaultColorDecorators: false,
  colorDecoratorsActivatedOn: "clickAndHover",
  inlineCompletionsAccessibilityVerbose: false,
  codeActionsOnSave: {},
  defaultFormatter: null,
  rename: {
    enablePreview: true,
  },
  codeActionWidget: {
    showHeaders: true,
    includeNearbyQuickFixes: true,
  },
  defaultFoldingRangeProvider: null,
  snippets: {
    codeActions: {
      enabled: true,
    },
  },
  formatOnSave: false,
  formatOnSaveMode: "file",
  overviewRulerLanes: 3,
  lineNumbersMinChars: 3,
  fixedOverflowWidgets: true,
  readOnly: false,
  renderValidationDecorations: "on",
  ariaLabel: "Editor",
};
